In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/test.csv')

In [3]:
df_train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [4]:
df_test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [5]:
# 'y' column is missing in the test dataset, Y column is the target column and the rest are features
# Shape of datasets

print('Shape of train dataset :',df_train.shape)
print('Shape of test dataset :', df_test.shape)

Shape of train dataset : (4209, 378)
Shape of test dataset : (4209, 377)


In [6]:
# Finding if there are null values in dataset

df_train.isnull().sum().any()

False

In [7]:
df_test.isnull().sum().any()

False

In [8]:

# There are no values in train and test dataframe
# Checking if any column has standard deviation = 0

df_train.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [11]:
# 'X11' column have std = 0, there might be more such columns
# Getting number of columns which has std = 0
(df_train.describe().iloc[2:3,:].T==0).T.sum()


ID      0
y       0
X10     0
X11     1
X12     0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 370, dtype: int64

In [14]:
# getting names of columns for which std = 0
df_std = (df_train.describe().iloc[2:3,:].T==0)
df_std.index[df_std['std'] == True]

Index(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293',
       'X297', 'X330', 'X347'],
      dtype='object')

In [20]:
# Dropping These columns from Train and test DataFrames
# Along with the ID column which is irrelevant

df_train.drop(columns={'ID', 'X11', 'X93', 'X107', 'X233' ,'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347'})
df_test.drop(columns={'ID', 'X11', 'X93', 'X107', 'X233' ,'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347'})

# Getting results in shapes

print('Shape of Train dataset :', df_train.shape)
print('Shape of Test dataset :', df_test.shape)

Shape of Train dataset : (4209, 378)
Shape of Test dataset : (4209, 377)


In [21]:
# Getting object columns in Train and Test Dfs
df_train.dtypes[df_train.dtypes == 'object'].index

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [22]:
df_test.dtypes[df_test.dtypes == 'object'].index

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [23]:
# Above listed are object columns in both datasets
# getting unique values for object columns

obj_cols = list(df_train.dtypes[df_train.dtypes == 'object'].index)
obj_cols

['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

In [24]:
for x in obj_cols:
    print('Unique values in df_train', [x], 'column :','\n', df_train[x].unique(),'\n')

Unique values in df_train ['X0'] column : 
 ['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab'] 

Unique values in df_train ['X1'] column : 
 ['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab'] 

Unique values in df_train ['X2'] column : 
 ['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar'] 

Unique values in df_train ['X3'] column : 
 ['a' 'e' 'c' 'f' 'd' 'b' 'g'] 

Unique values in df_train ['X4'] column : 
 ['d' 'b' 'c' 'a'] 

Unique values in df_train ['X5'] column : 
 ['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad' 'ae'
 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa'] 

Unique values in df_t

In [25]:
# above mentioned are column and unique values
# label encoding object columns in Train and Test both datasets

from sklearn.preprocessing import LabelEncoder
l_encode = LabelEncoder()
for x in obj_cols:
    df_train[x] = l_encode.fit_transform(df_train[x])
    df_test[x] = l_encode.fit_transform(df_test[x])
    

In [26]:
# Checking unique values after label encoding
for x in obj_cols:
    print('Unique values in df_train', [x], 'column :','\n', df_train[x].unique(),'\n')

Unique values in df_train ['X0'] column : 
 [32 20 40  9 36 43 31 29 39 35 19 27 44 45  7  8 10 46 37 15 12 42  5  0
 26  6 25 13 24  1 22 14 30 38 21 18 23 41  4 16 34 33 17 11  3 28  2] 

Unique values in df_train ['X1'] column : 
 [23 21 24  3 19 13 20  1  4  0  6  9 26 11 16 22 17 15 10 25  5  7 14 12
  8 18  2] 

Unique values in df_train ['X2'] column : 
 [17 19 34 25 16 14 38  7  8 33  0 31  3 39 26 24  5 21  2 13 27 29 20 42
 22 12  9 28 41 18 40 11 43  6 36 10 30 37  4 32  1 23 35 15] 

Unique values in df_train ['X3'] column : 
 [0 4 2 5 3 1 6] 

Unique values in df_train ['X4'] column : 
 [3 1 2 0] 

Unique values in df_train ['X5'] column : 
 [24 28 27 12 11 10 14 13  9  8  5  6  1  2  3  4  7 16 15 18 17 20 21 23
 22 25 26 19  0] 

Unique values in df_train ['X6'] column : 
 [ 9 11  3  7  8  0  6  2 10  4  5  1] 

Unique values in df_train ['X8'] column : 
 [14 23  4 13 18  0  7 15 12 10  3  8 21  9  1 16 22  6 24 11  5 20 17 19
  2] 



In [27]:
# Scaling the df_train
# First splitting target(y) from df_train

y = df_train['y']
x = df_train.drop(['y'],axis = 1)
print(y.head())
print(x.head())

0    130.81
1     88.53
2     76.26
3     80.62
4     78.02
Name: y, dtype: float64
   ID  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  X379  \
0   0  32  23  17   0   3  24   9  14    0  ...     0     0     1     0     0   
1   6  32  21  19   4   3  28  11  14    0  ...     1     0     0     0     0   
2   7  20  24  34   2   3  27   9  23    0  ...     0     0     0     0     0   
3   9  20  21  34   5   3  27  11   4    0  ...     0     0     0     0     0   
4  13  20  23  34   5   3  12   3  13    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 377 columns]


In [28]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()

In [29]:
# scaling x data
x = scale.fit_transform(x)

In [30]:
# visualising for confirmation
pd.DataFrame(x)

0         1         2         3         4    5         6    \
0     0.000000  0.695652  0.884615  0.395349  0.000000  1.0  0.857143   
1     0.000713  0.695652  0.807692  0.441860  0.666667  1.0  1.000000   
2     0.000832  0.434783  0.923077  0.790698  0.333333  1.0  0.964286   
3     0.001069  0.434783  0.807692  0.790698  0.833333  1.0  0.964286   
4     0.001544  0.434783  0.884615  0.790698  0.833333  1.0  0.428571   
...        ...       ...       ...       ...       ...  ...       ...   
4204  0.998574  0.173913  0.769231  0.372093  0.333333  1.0  0.000000   
4205  0.998693  0.673913  0.615385  0.930233  0.500000  1.0  0.000000   
4206  0.999406  0.173913  0.884615  0.883721  0.000000  1.0  0.000000   
4207  0.999762  0.195652  0.730769  0.581395  0.833333  1.0  0.000000   
4208  1.000000  1.000000  0.730769  0.069767  0.333333  1.0  0.000000   

           7         8    9    ...  367  368  369  370  371  372  373  374  \
0     0.818182  0.583333  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
1     1.000000  0.583333  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2     0.818182  0.958333  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
3     1.000000  0.166667  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.272727  0.541667  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...        ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4204  0.272727  0.666667  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4205  0.636364  0.291667  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4206  0.545455  0.166667  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
4207  1.000000  0.833333  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4208  0.545455  0.916667  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      375  376  
0     0.0  0.0  
1     0.0  0.0  
2     0.0  0.0  
3     0.0  0.0  
4     0.0  0.0  
...   ...  ...  
4204  0.0  0.0  
4205  0.0  0.0  
4206  0.0  0.0  
4207  0.0  0.0  
4208  0.0  0.0  

[4209 rows x 377 columns]

In [33]:
pd.DataFrame(x).describe()

0            1            2            3            4    \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.499698     0.646973     0.427445     0.402476     0.486616   
std       0.289605     0.298660     0.328115     0.253486     0.289985   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.248901     0.413043     0.115385     0.186047     0.333333   
50%       0.501366     0.760870     0.500000     0.372093     0.333333   
75%       0.750149     0.934783     0.769231     0.581395     0.833333   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               5            6            7            8            9    ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.999287     0.476437     0.618847     0.483805     0.013305  ...   
std       0.024633     0.294673     0.265179     0.293245     0.114590  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       1.000000     0.178571     0.545455     0.208333     0.000000  ...   
50%       1.000000     0.535714     0.636364     0.458333     0.000000  ...   
75%       1.000000     0.750000     0.818182     0.750000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

               367          368          369          370          371  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               372          373          374          375          376  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 377 columns]

In [34]:
# Dimensionality reduction using PCA
from sklearn.decomposition import PCA

In [35]:
pca = PCA(n_components = 0.95)  # Dimensionality reduction to keep 99% variance 
pca.fit(x)                      # Fitting train dataset (x) into PCA 
pca.explained_variance_ratio_   # Getting columns needed to keep 99% variance

array([0.12925156, 0.08720847, 0.08488187, 0.06723797, 0.05617423,
       0.0467907 , 0.03750601, 0.03229427, 0.02769919, 0.02467332,
       0.0230474 , 0.01943442, 0.01690012, 0.01624221, 0.01517821,
       0.01460336, 0.01370768, 0.01210093, 0.01026688, 0.01012063,
       0.00956797, 0.00897865, 0.00873228, 0.00837715, 0.00788144,
       0.00752548, 0.0072006 , 0.00649633, 0.00642396, 0.00607746,
       0.00558859, 0.00522622, 0.00502539, 0.0046775 , 0.00457035,
       0.00428642, 0.00420839, 0.00418772, 0.00400924, 0.00389396,
       0.00362183, 0.00345824, 0.0034199 , 0.00334766, 0.00329623,
       0.00314598, 0.00311526, 0.00296642, 0.00288872, 0.00281113,
       0.00269481, 0.00259407, 0.00257268, 0.0024333 , 0.00236016,
       0.00233437, 0.00225806, 0.00212766, 0.00208705, 0.00199738,
       0.00197213, 0.00195467, 0.00183163, 0.00178232, 0.00171997,
       0.00169971, 0.00164759, 0.00159813, 0.00158752, 0.00152489,
       0.00147452, 0.00144902, 0.00140683, 0.00138133, 0.00137

In [36]:
pca.explained_variance_.shape

(77,)

In [37]:
np.sum(pca.explained_variance_ratio_)

0.9507931047997226

In [38]:
# 76 columns carry 95% variance and hence dimensionality can be reduced from '365' to '76'
# Getting transformed train (x) dataset 

x_trans = pca.transform(x)
x_trans.shape

(4209, 77)

In [39]:
# Performing train test split  
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_trans, y, test_size = 0.25, random_state = 5)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(3156, 77)
(1053, 77)
(3156,)
(1053,)


In [40]:
# Model building using XGBoost
from xgboost import XGBRegressor
xgb_model = XGBRegressor()

In [1]:
xgb_model.fit(x_train, y_train)

NameError: name 'xgb_model' is not defined